# Dev configuration

# Auth files
[auth]
key = "configuration/hs256.json"

  [auth.cayley]
  store = "data/auth.graph"

[oauth]
google = "configuration/oauth_google.json"

[bolt]
store = "data/papernet.db"

[bleve]
store = "data/papernet.index"
