- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - nginx
    - jq
    - unzip

- name: Copy nginx configuration
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/sites-available/papernet.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  become: true

- name: Symlink the nginx configuration
  file:
    src: /etc/nginx/sites-available/papernet.conf
    dest: /etc/nginx/sites-enabled/papernet.conf
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  become: true

- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  become: true
  with_items:
    - /var/www/papernet
    - /var/www/papernet/data
    - /var/www/papernet/configuration

- name: Put papernet in systemd
  copy:
    src: papernet.service
    dest: /lib/systemd/system/papernet.service
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 644
  become: true

- name: Stop papernet
  service:
    name: papernet
    state: stopped
  become: true

- name: Push download script
  template:
    src: get_release.sh.j2
    dest: /var/www/papernet/get_release.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744
  become: true

- name: Execute download script
  shell: /var/www/papernet/get_release.sh
  args:
    chdir: /var/www/papernet

- name: Make binary executable
  file:
    path: "/var/www/papernet/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744
  with_items:
    - papernet-web
    - papernet-cli

- name: Copy configuration templates
  template:
    src: "{{ item.src }}"
    dest: "/var/www/papernet/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - { src: hs256.json.j2, dest: configuration/hs256.json }
    - { src: oauth_google.json.j2, dest: configuration/oauth_google.json }

- name: Copy configuration files
  copy:
    src: "{{ item.src }}"
    dest: "/var/www/papernet/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  with_items:
    - { src: config.prod.toml, dest: configuration/config.prod.toml }

- name: Restart nginx and papernet
  service:
    name: "{{ item }}"
    state: restarted
  with_items:
    - nginx
    - papernet
  become: true

