- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Set authorized key took from file
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"
