- name: Run the equivalent of "apt-get update" as a separate step
  apt:
    update_cache: yes
  become: true

- name: Set authorized key took from file
  authorized_key:
    user: vagrant
    state: present
    key: "{{ lookup('file', '~/.ssh/id_rsa.pub') }}"

- name:
  lineinfile:
    dest: /etc/hosts
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  become: true
  with_items:
    - { regexp: '^192.168.50.3 local-bobi.space$', line: "192.168.50.3 local-bobi.space" }
    - { regexp: '^192.168.50.3 api.local-bobi.space$', line: "192.168.50.3 api.local-bobi.space" }
    - { regexp: '^192.168.50.3 papernet.local-bobi.space$', line: "192.168.50.3 papernet.local-bobi.space" }
