- name: Install packages
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - nginx
    - jq
    - unzip

- name: Copy nginx configuration
  template:
    src: "{{ item.src }}"
    dest: "/etc/nginx/sites-available/{{ item.dest }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0644
  become: true
  with_items:
    - { src: nginx.conf.j2, dest: papernet-front.conf }
    - { src: nginx_default.conf.j2, dest: default.conf }

- name: Symlink the nginx configuration
  file:
    src: "/etc/nginx/sites-available/{{ item }}"
    dest: "/etc/nginx/sites-enabled/{{ item }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    state: link
  become: true
  with_items:
    - papernet-front.conf
    - default.conf

- name: Create needed directories
  file:
    path: "{{ item }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0755
  become: true
  with_items:
    - /var/www/papernet
    - /var/www/papernet/app

- name: Push download front script
  template:
    src: get_front.sh.j2
    dest: /var/www/papernet/get_front.sh
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0744
  become: true

- name: Execute download front script
  shell: /var/www/papernet/get_front.sh
  args:
    chdir: /var/www/papernet

- name: Unzip app
  unarchive:
    src: /var/www/papernet/papernet-front.zip
    dest: /var/www/papernet
    copy: no

- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
